#!/bin/bash

BATCH_GROUP=$(date +%Y-%m-%d)


PYTHONPATH=. luigi \
  --module scrape_rotten.luigi_tasks.scrape_reviews ScrapeReviews  \
  --batch-group $BATCH_GROUP \
  --local-scheduler

PYTHONPATH=. luigi \
  --module scrape_rotten.luigi_tasks.scrape_movies ScrapeMovies  \
  --batch-group $BATCH_GROUP \
  --local-scheduler

PYTHONPATH=. luigi \
  --module scrape_rotten.luigi_tasks.add_scrape_stats AddScrapeStats  \
  --batch-group $BATCH_GROUP \
  --local-scheduler
